#!/bin/sh
# Desktop environment
#gnome-settings-daemon &
#gnome-keyring-daemon
#/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
gnome-screensaver &
nm-applet &
xautolock -time 10 -locker "gnome-screensaver-command --lock" &
